export interface ILocalDeFuncionamento {
    campo_3: number | null,
    campo_4: number | null,
    campo_5: number | null,
    campo_6: number | null,
    campo_7: number | null,
    campo_8: number | null,
    campo_9: number | null,
    campo_10: number | null,
    campo_11: string,
    campo_12: string,
    campo_13: string,
    campo_14: string,
    campo_15: string,
    campo_16: string,
};

export interface IAbastecimentoDeAgua {
    campo_17: number | null,
    campo_18: number | null,
    campo_19: number | null,
    campo_20: number | null,
    campo_21: number | null,
    campo_22: 0 | 1,
}

export interface IEnergiaEletrica {
    campo_26: 0 | 1,
    campo_23: number | null,
    campo_24: number | null,
    campo_25: number | null,
}

export interface IEsgotamentoSanitario {
    campo_30: 0 | 1,
    campo_27: number | null,
    campo_28: number | null,
    campo_29: number | null,
}

export interface IDestinacaoDoLixo {
    campo_31: number | null,
    campo_32: number | null,
    campo_33: number | null,
    campo_34: number | null,
    campo_35: number | null,
}

export interface ITratamentoDoLixo {
    campo_39: 0 | 1,
    campo_36: number | null,
    campo_37: number | null,
    campo_38: number | null,

}
export interface IDependenciasFisicas {
    campo_77: 0 | 1,
    campo_40: number | null,
    campo_41: number | null,
    campo_42: number | null,
    campo_43: number | null,
    campo_44: number | null,
    campo_45: number | null,
    campo_46: number | null,
    campo_47: number | null,
    campo_48: number | null,
    campo_49: number | null,
    campo_50: number | null,
    campo_51: number | null,
    campo_52: number | null,
    campo_53: number | null,
    campo_54: number | null,
    campo_55: number | null,
    campo_56: number | null,
    campo_57: number | null,
    campo_58: number | null,
    campo_59: number | null,
    campo_60: number | null,
    campo_61: number | null,
    campo_62: number | null,
    campo_63: number | null,
    campo_64: number | null,
    campo_65: number | null,
    campo_66: number | null,
    campo_67: number | null,
    campo_68: number | null,
    campo_69: number | null,
    campo_70: number | null,
    campo_71: number | null,
    campo_72: number | null,
    campo_73: number | null,
    campo_74: number | null,
    campo_75: number | null,
    campo_76: number | null,
}
export interface IRecursosDeAcessibilidade {
    campo_86: 0 | 1,
    campo_78: number | null,
    campo_79: number | null,
    campo_80: number | null,
    campo_81: number | null,
    campo_82: number | null,
    campo_83: number | null,
    campo_84: number | null,
    campo_85: number | null,
    campo_87: string,
    campo_88: string,
    campo_89: string,
    campo_90: string,
}
export interface IEquipamentos {
    campo_97: 0 | 1,
    campo_91: number | null,
    campo_92: number | null,
    campo_93: number | null,
    campo_94: number | null,
    campo_95: number | null,
    campo_96: number | null,
}


export interface IAcessoInternet {
    campo_110: 0 | 1,
    campo_106: number | null,
    campo_107: number | null,
    campo_108: number | null,
    campo_109: number | null,
}
export interface IEquipamentosAlunosInternet {
    campo_111: number | null,
    campo_112: number | null,
    campo_113: number | null,
}
export interface IRedeLocal {
    campo_116: 0 | 1,
    campo_114: number | null,
    campo_115: number | null,
}

export interface IQuantidadeEquipamentos {
    campo_98: string,
    campo_99: string,
    campo_100: string,
    campo_101: string,
    campo_102: string,
    campo_103: string,
    campo_104: string,
    campo_105: string,
}
export interface ITotalProfissionais {
    campo_133: 0 | 1,
    campo_117: string,
    campo_118: string,
    campo_119: string,
    campo_120: string,
    campo_121: string,
    campo_122: string,
    campo_123: string,
    campo_124: string,
    campo_125: string,
    campo_126: string,
    campo_127: string,
    campo_128: string,
    campo_129: string,
    campo_130: string,
    campo_131: string,
    campo_132: string,
    campo_134: number | null,
}
export interface IInstrumentosEMateriais {
    campo_147: 0 | 1,
    campo_135: number | null,
    campo_136: number | null,
    campo_137: number | null,
    campo_138: number | null,
    campo_139: number | null,
    campo_140: number | null,
    campo_141: number | null,
    campo_142: number | null,
    campo_143: number | null,
    campo_144: number | null,
    campo_145: number | null,
    campo_146: number | null,
    campo_148: number | null,
}
export interface ILinguaMinistrada {
    campo_149: number | null,
    campo_150: number | null,
    campo_151: string,
    campo_152: string,
    campo_153: string
}
export interface IReservaDeVagas {
    campo_155: number | null,
    campo_156: number | null,
    campo_157: number | null,
    campo_158: number | null,
    campo_159: number | null,
    campo_160: 0 | 1,
    campo_161: number | null,
    campo_162: number | null,
    campo_163: number | null,
}
export interface IOrgaosColegiados {
    campo_169: 0 | 1,
    campo_164: number | null,
    campo_165: number | null,
    campo_166: number | null,
    campo_167: number | null,
    campo_168: number | null,
}

export interface IUltimasPerguntas {
    campo_154: number | null,
    campo_170: number | null
}


export interface IAllValues {
    campo_3: number | null,
    campo_4: number | null,
    campo_5: number | null,
    campo_6: number | null,
    campo_7: number | null,
    campo_8: number | null,
    campo_9: number | null,
    campo_10: number | null,
    campo_11: string,
    campo_12: string,
    campo_13: string,
    campo_14: string,
    campo_15: string,
    campo_16: string,
    campo_17: number | null,
    campo_18: number | null,
    campo_19: number | null,
    campo_20: number | null,
    campo_21: number | null,
    campo_22: 0 | 1,
    campo_23: number | null,
    campo_24: number | null,
    campo_25: number | null,
    campo_26: 0 | 1,
    campo_27: number | null,
    campo_28: number | null,
    campo_29: number | null,
    campo_30: 0 | 1,
    campo_31: number | null,
    campo_32: number | null,
    campo_33: number | null,
    campo_34: number | null,
    campo_35: number | null,
    campo_36: number | null,
    campo_37: number | null,
    campo_38: number | null,
    campo_39: 0 | 1,
    campo_40: number | null,
    campo_41: number | null,
    campo_42: number | null,
    campo_43: number | null,
    campo_44: number | null,
    campo_45: number | null,
    campo_46: number | null,
    campo_47: number | null,
    campo_48: number | null,
    campo_49: number | null,
    campo_50: number | null,
    campo_51: number | null,
    campo_52: number | null,
    campo_53: number | null,
    campo_54: number | null,
    campo_55: number | null,
    campo_56: number | null,
    campo_57: number | null,
    campo_58: number | null,
    campo_59: number | null,
    campo_60: number | null,
    campo_61: number | null,
    campo_62: number | null,
    campo_63: number | null,
    campo_64: number | null,
    campo_65: number | null,
    campo_66: number | null,
    campo_67: number | null,
    campo_68: number | null,
    campo_69: number | null,
    campo_70: number | null,
    campo_71: number | null,
    campo_72: number | null,
    campo_73: number | null,
    campo_74: number | null,
    campo_75: number | null,
    campo_76: number | null,
    campo_77: 0 | 1,
    campo_78: number | null,
    campo_79: number | null,
    campo_80: number | null,
    campo_81: number | null,
    campo_82: number | null,
    campo_83: number | null,
    campo_84: number | null,
    campo_85: number | null,
    campo_86: 0 | 1,
    campo_87: string,
    campo_88: string,
    campo_89: string,
    campo_90: string,
    campo_91: number | null,
    campo_92: number | null,
    campo_93: number | null,
    campo_94: number | null,
    campo_95: number | null,
    campo_96: number | null,
    campo_97: 0 | 1,
    campo_98: string,
    campo_99: string,
    campo_100: string,
    campo_101: string,
    campo_102: string,
    campo_103: string,
    campo_104: string,
    campo_105: string,
    campo_106: number | null,
    campo_107: number | null,
    campo_108: number | null,
    campo_109: number | null,
    campo_110: 0 | 1,
    campo_111: number | null,
    campo_112: number | null,
    campo_113: number | null,
    campo_114: number | null,
    campo_115: number | null,
    campo_116: 0 | 1,
    campo_117: string,
    campo_118: string,
    campo_119: string,
    campo_120: string,
    campo_121: string,
    campo_122: string,
    campo_123: string,
    campo_124: string,
    campo_125: string,
    campo_126: string,
    campo_127: string,
    campo_128: string,
    campo_129: string,
    campo_130: string,
    campo_131: string,
    campo_132: string,
    campo_133: 0 | 1,
    campo_134: number | null,
    campo_135: number | null,
    campo_136: number | null,
    campo_137: number | null,
    campo_138: number | null,
    campo_139: number | null,
    campo_140: number | null,
    campo_141: number | null,
    campo_142: number | null,
    campo_143: number | null,
    campo_144: number | null,
    campo_145: number | null,
    campo_146: number | null,
    campo_147: 0 | 1,
    campo_148: number | null,
    campo_149: number | null,
    campo_150: number | null,
    campo_151: string,
    campo_152: string,
    campo_153: string,
    campo_154: number | null,
    campo_155: number | null,
    campo_156: number | null,
    campo_157: number | null,
    campo_158: number | null,
    campo_159: number | null,
    campo_160: 0 | 1,
    campo_161: number | null,
    campo_162: number | null,
    campo_163: number | null,
    campo_164: number | null,
    campo_165: number | null,
    campo_166: number | null,
    campo_167: number | null,
    campo_168: number | null,
    campo_169: 0 | 1,
    campo_170: number | null,
    inep_fk: string | undefined,
}